apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/
- namespace.yaml
patchesStrategicMerge:
- db.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: mysql
    name: db
  path: data.yaml
